name: Docs

on:
  pull_request: {}
  push: { branches: [main, master, develop] }

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish_doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'

    - name: Build doc
      working-directory: docs
      run: mdbook build

    - name: Move book to home
      working-directory: docs
      run: mv ./book/ ~/

    - name: Checkout document repository
      uses: actions/checkout@v3
      with:
        ref: 'gh-pages'

    - name: Move book to repository
      run: |
        mv -rf ./*
        mv -f ~/book/* ./

    - name: Set git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Commit
      continue-on-error: true
      run: |
        git pull
        git add .
        git commit -m "Update doc - ${{ github.event.repository.name }}"
        git push origin
