name: 📦 Source

on:
  pull_request: {}
  push: { branches: [main, master, develop] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_VERSION: 2021.1.1f1
  PROJECT_PATH: ./Source
  ULF_FILE: Unity_v2021.x.ulf
  NEXT_VERSION: 1.3.0
  BUILD_METHOD: PackageExporter.BatchMode.Export

jobs:
  package:
    name: Package all packages
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2021.1.21f1-android-0.15.0
    strategy:
      matrix:
        package-name:
          - PackageExporter
        targetPlatform:
          - StandaloneLinux64
    steps:
      - uses: actions/checkout@v1
        with:
          lfs: true

      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library-test-project-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-test-project-
            Library-

      - uses: game-ci/unity-builder@v2.0-alpha-13
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildMethod: ${{ env.BUILD_METHOD }}
          customParameters: -nographics --name "${{ matrix.package-name }}" --version "${{ env.NEXT_VERSION }}" --savePath "."

      - name: Print current directory
        run: ls -a ${{ env.PROJECT_PATH }}

      - name: Upload package as artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.package-name }}
          path: ${{ env.PROJECT_PATH }}/${{ matrix.package-name }}.unitypackage
